universe = vanilla
executable = condor.sh
initialdir = neu_10GeV
arguments = $(ProcId)
output =  log/$(ProcId).out
error = log/$(ProcId).err
log = log/$(ProcId).log
request_memory = 1 GB

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = /d0/scratch/chanchoen/DRC_generic/install/bin, /d0/scratch/chanchoen/DRC_generic/install/lib, /d0/scratch/chanchoen/DRC_generic/install/init.mac, /d0/scratch/chanchoen/DRC_generic/install/run_ele.mac

queue 250
